const Products = [
    {
      id: 1,
      image: 'https://via.placeholder.com/300',
      name: 'Wireless Headphones',
      price: 49.99,
      originalPrice: 79.99,
      discount: 20,
    },
    {
      id: 2,
      image: 'https://via.placeholder.com/300',
      name: 'Smartwatch',
      price: 99.99,
      originalPrice: 149.99,
      discount: 33,
    },
    {
      id: 3,
      image: 'https://via.placeholder.com/300',
      name: 'Gaming Mouse',
      price: 29.99,
      originalPrice: 39.99,
      discount: 25,
    },
    {
      id: 4,
      image: 'https://via.placeholder.com/300',
      name: 'Mechanical Keyboard',
      price: 89.99,
      originalPrice: 119.99,
      discount: 25,
    },
    {
      id: 5,
      image: 'https://via.placeholder.com/300',
      name: 'Bluetooth Speaker',
      price: 59.99,
      originalPrice: 89.99,
      discount: 33,
    },
    {
      id: 6,
      image: 'https://via.placeholder.com/300',
      name: 'Smartphone',
      price: 499.99,
      originalPrice: 699.99,
      discount: 29,
    },
    // {
    //   id: 7,
    //   image: 'https://via.placeholder.com/300',
    //   name: 'Tablet',
    //   price: 299.99,
    //   originalPrice: 399.99,
    //   discount: 25,
    // },
    // {
    //   id: 8,
    //   image: 'https://via.placeholder.com/300',
    //   name: 'Gaming Laptop',
    //   price: 999.99,
    //   originalPrice: 1299.99,
    //   discount: 23,
    // },
  ];
  
  export default Products;